name: gvite-nightly-build

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      tag:
        type: string
        required: true  
  workflow_dispatch:
    inputs:
      branch:
        description: 'nightly build from'
        required: true
      tag:
        description: 'tag prefix'
        required: true

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Set branch and tag
      id: step0
      run: |
        echo "::set-output name=branch::${{ (inputs || github.event.inputs).branch }}"
        echo "::set-output name=tag::${{ (inputs || github.event.inputs).tag }}"

    - name: Echo branch and tag
      run: echo ${{ steps.step0.outputs.branch }} ${{ steps.step0.outputs.tag }}

    - uses: actions/checkout@v2
      with:
        repository: 'blake256/go-vite'
        ref: '${{ github.event.inputs.branch }}'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
 
    - name: Test
      run: make test
       
    - name: Get Build Version
      id: version
      run: echo "::set-output name=version::$(date +%Y%m%d%H%M)"
      
    - name: Build
      run:  echo "${{ github.event.inputs.tag }}-nightly-${{ steps.version.outputs.version }}" > version/buildversion ; make all
      
    - name: Release Log
      run: cd build/cmd/gvite ;ls | grep -v ".tar.gz" | while read line; do tar zcvf $line.tar.gz $line ; openssl dgst -sha256 $line.tar.gz >> release.sha256.log ;done ; cd ../../../ 
      
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        tag: "${{ github.event.inputs.tag }}-nightly-${{ steps.version.outputs.version }}"
        artifacts: "build/cmd/gvite/*.tar.gz"
        bodyFile: "build/cmd/gvite/release.sha256.log"
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
