name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    needs: job1
    uses: ./.github/workflows/govite-nightly-build.yml
    with:
      branch: ${{needs.job1.outputs.output1}}
      tag: ${{needs.job1.outputs.output2}}
