name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.buildversion }}
    steps:
      - name: Read buildversion
        id: buildversion
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version/buildversion    
      - id: step1
        run: echo "::set-output name=buildversion::${{ steps.buildversion.outputs.buildversion }}"
  job2:
    needs: job1
    uses: ./.github/workflows/govite-nightly-build.yml
    with:
      branch: main
      tag: ${{needs.job1.outputs.output1}}
