name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 'ref:' ${{ github.event.client_payload.ref }} ' / sha:' ${{ github.event.client_payload.sha }}
