name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
jobs:
  test1:
    uses: ./.github/workflows/govite-nightly-build.yml
    with:
      branch: main
      tag: v1234
