name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
jobs:
  run_nightly:
    uses: ./.github/workflows/govite-nightly-build.yml
    name: Run govite-nightly-build
    with:
      branch: master
      version: 1234
