name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
jobs:
  test1:
    uses: blake256/nightly-test/.github/workflows/govite-nightly-build.yml@main
    with:
      branch: main
      tag: v1234
