name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/govite-nightly-build.yml
        with:
          branch: master
          version: 1234
  test2:
    uses: ./.github/workflows/govite-nightly-build.yml
    name: Run govite-nightly-build
    with:
      branch: master
      version: 1234
