name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'    
      - uses: ./.github/workflows/govite-nightly-build.yml
        with:
          branch: master
          version: 1234
