name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/govite-nightly-build.yml
        with:
          branch: master
          tag: v1234
