name: wf2

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      tag:
        type: string
        required: true  
  workflow_dispatch:
    inputs:
      branch:
        description: 'nightly build from'
        required: true
      tag:
        description: 'tag prefix'
        required: true
        
jobs:
  test_job:
    runs-on: ubuntu-18.04
    steps:
    - name: Set branch and tag
      id: step0
      run: echo "::set-output name=tag::${{ (inputs || github.event.inputs).tag }}" | echo "::set-output name=branch::${{ (inputs || github.event.inputs).branch }}"
    - name: Echo branch and tag
      run: echo ${{ steps.step0.outputs.tag }} ${{ steps.step0.outputs.branch }}
