name: wf2

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      tag:
        type: string
        required: true  
  workflow_dispatch:
    inputs:
      branch:
        description: 'nightly build from'
        required: true
      tag:
        description: 'tag prefix'
        required: true
        
 jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Set branch and tag
      id: step0
      run: echo "::set-output name=branch::${{ (inputs || github.event.inputs).branch }}" | echo "::set-output name=branch::${{ (inputs || github.event.inputs).tag }}"
    - name: Echo branch and tag
      run:  echo "branch: ${{ steps.step0.outputs.branch }} tag: ${{ steps.step0.outputs.tag }}"
